### PR TITLE
hellochain: fix issues with hellochain

### LINKED ISSUE #196: Tutorial missing hccli (used on one page but not created)
Hi,

I'm following your basic tutorial and on:

https://github.com/cosmos/sdk-tutorials/blob/master/hellochain/tutorial/04-try-it-out.md

it says I should try both hcd and hccli but on:

https://github.com/cosmos/sdk-tutorials/blob/master/hellochain/tutorial/02-simple-start.md

it only includes the code for hcd so hccli is not working when I get to step 4 (unless I'm missing something)

Thanks

### PR DESCRIPTION
**Pull request by marbar3778**
- closes #196

Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

### CODE REVIEW

File: hellochain/init.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+echo "12345678" | hccli keys add test2
+
+hcd add-genesis-account $(hccli keys show test1 -a) 10000000000000000000000000stake,1000000hello
+hcd add-genesis-account $(hccli keys show test2 -a) 100000000000stake,1000hello
+
+hccli config output json
+hccli config indent true
+hccli config trust-node true
+
+hcd start
```
Comment (hschoenburg) [inline hellochain/init.sh]: wow this script was a great idea
